project_id = "edjqlzzptewjsuutfafj"
[functions.ia-chat]
enabled = true
verify_jwt = true
import_map = "./functions/ia-chat/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ia-chat/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ia-chat/*.html" ]

[functions.twilio-send-message]
enabled = true
verify_jwt = true
import_map = "./functions/twilio-send-message/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/twilio-send-message/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/twilio-send-message/*.html" ]
