// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edjqlzzptewjsuutfafj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkanFsenpwdGV3anN1dXRmYWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDcwMzgsImV4cCI6MjA2OTcyMzAzOH0.eGR6GKdNcNi3xpLXH6j0Om2IRm27k6K42OIl37kVAbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});